language: ruby

rvm:
- 2.3.3
- 2.4.0


before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "gem update --system"
  - "gem update bundler"

script:
  - export NVM_DIR="$HOME/.nvm"
  - git clone https://github.com/creationix/nvm.git "$NVM_DIR" && cd "$NVM_DIR"
  - git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin` && . "$NVM_DIR/nvm.sh"
  - nvm install node
  - nvm use node
  - npm install apn
  - "sudo -u postgres createuser -s soulcast"
  - sudo -u postgres psql -c "ALTER USER soulcast WITH PASSWORD 'soulcast';"
  - bin/rake db:setup
  - bin/rake spec
cache: bundler

services:
  - postgresql

addons:
  postgresql: "9.6"

sudo: "required" #for 14.04
dist: "trusty"
